services:
  todo-app:
    build:
      context: ./app
    depends_on:
      - todo-database
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 35729:35729

  todo-database:
    image: mongo:6
    ports:
      - 27017:27017

