FROM node:19.5.0-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

FROM node:19.5.0-alpine

WORKDIR /app

COPY --from=build /app /app

EXPOSE 3000

CMD ["npm","start"]

