services:
  todo-app: #서비스 정의
    build: ./app #도커파일이 있는 디렉토리 경로
    ports: #포트매핑(호스트:컨테이너)
      - "3000:3000" #호스트의 포트 3000을 컨테이너 포트 3000에 연결, HTTP
      - "35729:35729" # 위와 동일, 소스코드 수정시 자동 새로고침되는 기능(라이브리로드)를 위함
    environment: #환경 변수 설정
      NODE_ENV: production #NODE_ENV 환경 변수를 production으로 설정
    depends_on: #서비스간의 의존성
      - todo-database #todo-database 서비스가 먼저 실행되어야 함을 명시

    #volumes: #로컬디렛토리와 컨테이너 내부 디렉토리를 연결할 수 있는 볼륨 설정
    #  - ./web:/usr/src/app #./web 디렉토리가 컨테이너 내부의 /usr/src/app에 마운트됨
    #networks: #커스텀 네트워크 설정을 사용할 수 있는 부분
    #  - my_network #my_network라는 사용자 정의 네트워크에 연결

  todo-database:
   image: mongo:6 #몽고6이미지를 이용해 몽고디비의 디비를 실행
   ports: #호스트와 컨테이너 간의 포트매핑 설정
      - 27017:27017 #호스트의 포트 27017을 컨테이너 포트 27017에 연결, 
                    #이는 몽고디비 기본포트로, 외부에서 몽고디비 접근 가능하도록 설정
